version: '3.8'

services:
  copera_ai:
    container_name: copera_ai
    image: node:18.12.1-alpine
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'yarn install && yarn build && yarn dev'
    ports:
      - '4000:4000'
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_PORT: ${APP_PORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - prv-net

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  prv-net:
    driver: bridge
